default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "rails_academy_checklist_development") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME", "rails_academy_checklist_test") %>

production:
  primary: &primary_production
    <<: *default
    database: rails_academy_checklist_production
    username: rails_academy_checklist
    password: <%= ENV["RAILS_ACADEMY_CHECKLIST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rails_academy_checklist_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rails_academy_checklist_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rails_academy_checklist_production_cable
    migrations_paths: db/cable_migrate